application-name: @project.artifactId@
application-description: @project.description@
application-version: @project.version@

server:
  port: 8080
  servlet:
    context-path: /shopping-cart/api/${shopping-cart.api.version}

spring:
  application:
    name: shopping-cart
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:9090
  datasource:
    url: "jdbc:h2:mem:testdb"
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 100

item-storage:
  hostname: item-storage
  port: 8080
  api:
    url: http://${item-storage.hostname}:${item-storage.port}/item-storage/api/${item-storage.api.version}
    version: v1

shopping-cart:
  api:
    version: v1

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

